#!/bin/sh

# correctly set remote url to use ssh
yadm remote set-url origin git@github.com:Yuslo22/dotfiles.git

# ZSH Plugins
if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.zsh/zsh-autosuggestions
fi
if [ ! -d "$HOME/.zsh/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
fi

# install fnm
curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
